import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "~/components/theme-provider";
import { HydrateClient } from "~/trpc/server";
import { SessionProvider } from "next-auth/react";
import PageLayout from "~/components/PageLayout";
import LayoutWrapper from "./layoutWrapper";
import { Toaster } from "~/components/ui/sonner";
import SessionWrapper from "./sessionWrapper";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${geist.variable}`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>
            <HydrateClient>
              <SessionWrapper>{children}</SessionWrapper>
              <Toaster />
            </HydrateClient>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
